// import ErrorWrapper from "./error-wrapper";
import { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import "./styles.css";
import Search from "@/components/search";
import { Navigation } from "@/components/navigation";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <ThemeProvider>
          <body>
            <header
              style={{
                backgroundColor: "lightblue",
                padding: "1rem",
              }}
            >
              <Navigation />
              <Search />
            </header>
            {/* <ErrorWrapper> */}
            {children}
            {/* </ErrorWrapper> */}
            <footer
              style={{
                backgroundColor: "ghostwhite",
                padding: "1rem",
              }}
            >
              <p>Footer</p>
            </footer>
          </body>
        </ThemeProvider>
      </html>
    </ClerkProvider>

  );
}