import { Counter } from "@/components/counter";
import { Metadata } from "next";
import Link from "next/link"

export const generateMetadata = async (): Promise<Metadata> => {
    return {
        title: {
            default: "Next.js",
            template: "%s | Next app",
        },
        description: "Generated by Next.js",
    };
};

const Home = () => <div className="page-wrapper">
    <h1>Welcome home!</h1>
    <Counter />
    <div className="links-wrapper">
        <ul className="flex">
            <li className="mr-6">
                <Link className="text-blue-500 hover:text-blue-800" href="/articles/breaking-news-123?lang=en">Articles English</Link>
            </li>
            <li className="mr-6">
                <Link className="text-blue-500 hover:text-blue-800" href="/articles/breaking-news-123?lang=fr">Articles French</Link>
            </li>
            <li className="mr-6">
                <Link className="text-blue-500 hover:text-blue-800" href="/blog">Blog</Link>
            </li>
            <li className="mr-6">
                <Link className="text-blue-500 hover:text-blue-800" href="/products">Products</Link>
            </li>
            <li className="mr-6">
                <Link className="text-blue-500 hover:text-blue-800" href="/blog">Blog</Link>
            </li>
        </ul>
    </div>
</div>

export default Home 